openapi: 3.0.1
info:
  title: Simple Copilot Plugin
  version: 1.0.0
  description: A basic API that returns user info
servers:
  - url: https://example.com  # Replace this with your actual API URL later
paths:
  /api/me:
    get:
      summary: Get user info
      operationId: getUserInfo
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: Rishika Singh
                  role:
                    type: string
                    example: Software Engineer Intern
