


openapi: 3.1.0
info:
  title: Simple Copilot API
  version: 1.0.0
paths:
  /api/me:
    get:
      summary: Get user info
      operationId: getUserInfo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  role:
                    type: string
